# Generated by Django 5.1 on 2024-08-25 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date_mya', models.IntegerField()),
                ('end_date_mya', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('systems', models.ManyToManyField(blank=True, related_name='organs', to='core.organsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genesis_mya', models.IntegerField()),
                ('extinction_mya', models.IntegerField()),
                ('lifetime_years', models.PositiveIntegerField()),
                ('inorganic_energy_source', models.CharField(choices=[('chemo', 'chemo'), ('sunlight', 'sunlight')], max_length=16)),
                ('ancestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descendants', to='core.species')),
                ('biome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species', to='core.biome')),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='species', to='core.continent')),
                ('organs', models.ManyToManyField(blank=True, related_name='species', to='core.organ')),
                ('preys_upon', models.ManyToManyField(blank=True, to='core.species')),
            ],
        ),
    ]
