# Generated by Django 5.1 on 2024-08-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
        migrations.AlterField(
            model_name='species',
            name='inorganic_energy_source',
            field=models.CharField(blank=True, choices=[('chemo', 'chemo'), ('sunlight', 'sunlight')], max_length=16, null=True),
        ),
    ]
