# Generated by Django 5.1 on 2024-08-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_species_organs_organ_species'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Continent',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='extinction_mya',
            new_name='extinction_date_mya',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='genesis_mya',
            new_name='genesis_date_mya',
        ),
        migrations.RenameField(
            model_name='species',
            old_name='continent',
            new_name='region',
        ),
    ]
